#!/bin/bash

input_file="../labels.txt"
mkdir -p Dataset/{Bing,Flickr,Google,Instagram}

while read label; do
    python "bing.py" -o "Dataset/Bing" -k "${label/$'\r'/}"
    echo
    python "flickr.py" -o "Dataset/Flickr" -k "${label/$'\r'/}"
    echo
    python "instagram.py" -o "Dataset/Instagram" -k "${label/$'\r'/}"
    echo
done <"$input_file"
